#!/usr/bin/env sh

# Speculative smoothing defense hyperparameters.
# This file only sets environment variables; run entrypoint handles execution.

export DEFENSE_NAME="${DEFENSE_NAME:-speculative_smoothing}"

export SPEC_SMOOTHING_TOP_K_LENSES="${SPEC_SMOOTHING_TOP_K_LENSES:-2}"
export SPEC_SMOOTHING_BRANCHES_PER_LENS="${SPEC_SMOOTHING_BRANCHES_PER_LENS:-2}"
export SPEC_SMOOTHING_SEED="${SPEC_SMOOTHING_SEED:-42}"
export SPEC_SMOOTHING_USE_FRESH_SEED="${SPEC_SMOOTHING_USE_FRESH_SEED:-1}"
export SPEC_SMOOTHING_AGGREGATOR="${SPEC_SMOOTHING_AGGREGATOR:-cvar}"
export SPEC_SMOOTHING_CVAR_ALPHA="${SPEC_SMOOTHING_CVAR_ALPHA:-0.5}"
export SPEC_SMOOTHING_DISAGREEMENT_WEIGHT="${SPEC_SMOOTHING_DISAGREEMENT_WEIGHT:-0.25}"
export SPEC_SMOOTHING_BLOCK_THRESHOLD="${SPEC_SMOOTHING_BLOCK_THRESHOLD:-0.70}"
export SPEC_SMOOTHING_ESCALATE_THRESHOLD="${SPEC_SMOOTHING_ESCALATE_THRESHOLD:-0.45}"
export SPEC_SMOOTHING_LENS_JITTER="${SPEC_SMOOTHING_LENS_JITTER:-0.15}"
export SPEC_SMOOTHING_LOG_DECISIONS="${SPEC_SMOOTHING_LOG_DECISIONS:-1}"

# Draft side (default: OpenRouter via main client).
export SPEC_SMOOTHING_DRAFT_BACKEND="${SPEC_SMOOTHING_DRAFT_BACKEND:-llm}"
export SPEC_SMOOTHING_DRAFT_MODEL="${SPEC_SMOOTHING_DRAFT_MODEL:-meta-llama/llama-3.2-3b-instruct}"
export SPEC_SMOOTHING_DRAFT_USE_MAIN_CLIENT="${SPEC_SMOOTHING_DRAFT_USE_MAIN_CLIENT:-1}"
export SPEC_SMOOTHING_DRAFT_BASE_URL="${SPEC_SMOOTHING_DRAFT_BASE_URL:-}"
export SPEC_SMOOTHING_DRAFT_API_KEY_ENV="${SPEC_SMOOTHING_DRAFT_API_KEY_ENV:-OPENROUTER_API_KEY}"
export SPEC_SMOOTHING_DRAFT_TEMPERATURE="${SPEC_SMOOTHING_DRAFT_TEMPERATURE:-0.7}"
export SPEC_SMOOTHING_DRAFT_MAX_TOKENS="${SPEC_SMOOTHING_DRAFT_MAX_TOKENS:-24}"
export SPEC_SMOOTHING_DRAFT_TOP_LOGPROBS_K="${SPEC_SMOOTHING_DRAFT_TOP_LOGPROBS_K:-8}"
export SPEC_SMOOTHING_DRAFT_NOISE_STD="${SPEC_SMOOTHING_DRAFT_NOISE_STD:-0.35}"
export SPEC_SMOOTHING_DRAFT_BRANCH_MIN_TOKENS="${SPEC_SMOOTHING_DRAFT_BRANCH_MIN_TOKENS:-8}"
export SPEC_SMOOTHING_DRAFT_BRANCH_MAX_TOKENS="${SPEC_SMOOTHING_DRAFT_BRANCH_MAX_TOKENS:-12}"

# Verifier side.
export SPEC_SMOOTHING_VERIFIER_BACKEND="${SPEC_SMOOTHING_VERIFIER_BACKEND:-tree_attention}"
export SPEC_SMOOTHING_VERIFIER_MODEL="${SPEC_SMOOTHING_VERIFIER_MODEL:-meta-llama/llama-3.1-8b-instruct}"
export SPEC_SMOOTHING_VERIFIER_TEMPERATURE="${SPEC_SMOOTHING_VERIFIER_TEMPERATURE:-0.0}"
export SPEC_SMOOTHING_VERIFIER_MAX_TOKENS="${SPEC_SMOOTHING_VERIFIER_MAX_TOKENS:-256}"

# Local tree verifier runtime.
export SPEC_SMOOTHING_VERIFIER_TREE_MODEL_NAME_OR_PATH="${SPEC_SMOOTHING_VERIFIER_TREE_MODEL_NAME_OR_PATH:-meta-llama/Llama-3.1-8B-Instruct}"
export SPEC_SMOOTHING_VERIFIER_TREE_DEVICE="${SPEC_SMOOTHING_VERIFIER_TREE_DEVICE:-cuda}"
export SPEC_SMOOTHING_VERIFIER_TREE_DTYPE="${SPEC_SMOOTHING_VERIFIER_TREE_DTYPE:-bf16}"
export SPEC_SMOOTHING_VERIFIER_TREE_STRICT="${SPEC_SMOOTHING_VERIFIER_TREE_STRICT:-1}"

# Client defaults for llm verifier fallback path.
export SPEC_SMOOTHING_API_KEY_ENV="${SPEC_SMOOTHING_API_KEY_ENV:-$API_KEY_ENV}"
export SPEC_SMOOTHING_BASE_URL="${SPEC_SMOOTHING_BASE_URL:-$BASE_URL}"
